compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

# See https://github.com/TanStack/router/issues/3778
packageExtensions:
  '@tanstack/react-router-devtools@^1.120.6':
    dependencies:
      '@tanstack/router-core': '^1.120.5'
      'tiny-invariant': '^1.3.3'

yarnPath: .yarn/releases/yarn-4.9.1.cjs
